/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteRouteImport } from './routes/_dashboardLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusSlugRouteImport } from './routes/status/$slug'
import { Route as OrganizationOrganizationViewRouteImport } from './routes/organization/$organizationView'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRecoverAccountRouteImport } from './routes/auth/recover-account'
import { Route as AuthMagicLinkRouteImport } from './routes/auth/magic-link'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailOtpRouteImport } from './routes/auth/email-otp'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAcceptInvitationRouteImport } from './routes/auth/accept-invitation'
import { Route as AuthRouteRouteImport } from './routes/auth/_route'
import { Route as AccountAccountViewRouteImport } from './routes/account/$accountView'
import { Route as DashboardLayoutStatusPagesIndexRouteImport } from './routes/_dashboardLayout/status-pages/index'
import { Route as DashboardLayoutMonitorsIndexRouteImport } from './routes/_dashboardLayout/monitors/index'
import { Route as DashboardLayoutIntegrationsIndexRouteImport } from './routes/_dashboardLayout/integrations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardLayoutStatusPagesCreateRouteImport } from './routes/_dashboardLayout/status-pages/create'
import { Route as DashboardLayoutStatusPagesStatusPageIdRouteImport } from './routes/_dashboardLayout/status-pages/$statusPageId'
import { Route as DashboardLayoutMonitorsAddRouteImport } from './routes/_dashboardLayout/monitors/add'
import { Route as DashboardLayoutMonitorsMonitorIdRouteImport } from './routes/_dashboardLayout/monitors/$monitorId'

const AuthRouteImport = createFileRoute('/auth')()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRouteRoute = DashboardLayoutRouteRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrganizationViewRoute =
  OrganizationOrganizationViewRouteImport.update({
    id: '/organization/$organizationView',
    path: '/organization/$organizationView',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecoverAccountRoute = AuthRecoverAccountRouteImport.update({
  id: '/recover-account',
  path: '/recover-account',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailOtpRoute = AuthEmailOtpRouteImport.update({
  id: '/email-otp',
  path: '/email-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAcceptInvitationRoute = AuthAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_route',
  getParentRoute: () => AuthRoute,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutStatusPagesIndexRoute =
  DashboardLayoutStatusPagesIndexRouteImport.update({
    id: '/status-pages/',
    path: '/status-pages/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMonitorsIndexRoute =
  DashboardLayoutMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutIntegrationsIndexRoute =
  DashboardLayoutIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutStatusPagesCreateRoute =
  DashboardLayoutStatusPagesCreateRouteImport.update({
    id: '/status-pages/create',
    path: '/status-pages/create',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutStatusPagesStatusPageIdRoute =
  DashboardLayoutStatusPagesStatusPageIdRouteImport.update({
    id: '/status-pages/$statusPageId',
    path: '/status-pages/$statusPageId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMonitorsAddRoute =
  DashboardLayoutMonitorsAddRouteImport.update({
    id: '/monitors/add',
    path: '/monitors/add',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMonitorsMonitorIdRoute =
  DashboardLayoutMonitorsMonitorIdRouteImport.update({
    id: '/monitors/$monitorId',
    path: '/monitors/$monitorId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth': typeof AuthRouteRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-otp': typeof AuthEmailOtpRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/status/$slug': typeof StatusSlugRoute
  '/monitors/$monitorId': typeof DashboardLayoutMonitorsMonitorIdRoute
  '/monitors/add': typeof DashboardLayoutMonitorsAddRoute
  '/status-pages/$statusPageId': typeof DashboardLayoutStatusPagesStatusPageIdRoute
  '/status-pages/create': typeof DashboardLayoutStatusPagesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations': typeof DashboardLayoutIntegrationsIndexRoute
  '/monitors': typeof DashboardLayoutMonitorsIndexRoute
  '/status-pages': typeof DashboardLayoutStatusPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth': typeof AuthRouteRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-otp': typeof AuthEmailOtpRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/status/$slug': typeof StatusSlugRoute
  '/monitors/$monitorId': typeof DashboardLayoutMonitorsMonitorIdRoute
  '/monitors/add': typeof DashboardLayoutMonitorsAddRoute
  '/status-pages/$statusPageId': typeof DashboardLayoutStatusPagesStatusPageIdRoute
  '/status-pages/create': typeof DashboardLayoutStatusPagesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations': typeof DashboardLayoutIntegrationsIndexRoute
  '/monitors': typeof DashboardLayoutMonitorsIndexRoute
  '/status-pages': typeof DashboardLayoutStatusPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteRouteWithChildren
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/_route': typeof AuthRouteRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-otp': typeof AuthEmailOtpRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/status/$slug': typeof StatusSlugRoute
  '/_dashboardLayout/monitors/$monitorId': typeof DashboardLayoutMonitorsMonitorIdRoute
  '/_dashboardLayout/monitors/add': typeof DashboardLayoutMonitorsAddRoute
  '/_dashboardLayout/status-pages/$statusPageId': typeof DashboardLayoutStatusPagesStatusPageIdRoute
  '/_dashboardLayout/status-pages/create': typeof DashboardLayoutStatusPagesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboardLayout/integrations/': typeof DashboardLayoutIntegrationsIndexRoute
  '/_dashboardLayout/monitors/': typeof DashboardLayoutMonitorsIndexRoute
  '/_dashboardLayout/status-pages/': typeof DashboardLayoutStatusPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/$accountView'
    | '/auth'
    | '/auth/accept-invitation'
    | '/auth/callback'
    | '/auth/email-otp'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/organization/$organizationView'
    | '/status/$slug'
    | '/monitors/$monitorId'
    | '/monitors/add'
    | '/status-pages/$statusPageId'
    | '/status-pages/create'
    | '/api/auth/$'
    | '/integrations'
    | '/monitors'
    | '/status-pages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/$accountView'
    | '/auth'
    | '/auth/accept-invitation'
    | '/auth/callback'
    | '/auth/email-otp'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/organization/$organizationView'
    | '/status/$slug'
    | '/monitors/$monitorId'
    | '/monitors/add'
    | '/status-pages/$statusPageId'
    | '/status-pages/create'
    | '/api/auth/$'
    | '/integrations'
    | '/monitors'
    | '/status-pages'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/account/$accountView'
    | '/auth'
    | '/auth/_route'
    | '/auth/accept-invitation'
    | '/auth/callback'
    | '/auth/email-otp'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/organization/$organizationView'
    | '/status/$slug'
    | '/_dashboardLayout/monitors/$monitorId'
    | '/_dashboardLayout/monitors/add'
    | '/_dashboardLayout/status-pages/$statusPageId'
    | '/_dashboardLayout/status-pages/create'
    | '/api/auth/$'
    | '/_dashboardLayout/integrations/'
    | '/_dashboardLayout/monitors/'
    | '/_dashboardLayout/status-pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
  AccountAccountViewRoute: typeof AccountAccountViewRoute
  AuthRoute: typeof AuthRouteWithChildren
  OrganizationOrganizationViewRoute: typeof OrganizationOrganizationViewRoute
  StatusSlugRoute: typeof StatusSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$organizationView': {
      id: '/organization/$organizationView'
      path: '/organization/$organizationView'
      fullPath: '/organization/$organizationView'
      preLoaderRoute: typeof OrganizationOrganizationViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/recover-account': {
      id: '/auth/recover-account'
      path: '/recover-account'
      fullPath: '/auth/recover-account'
      preLoaderRoute: typeof AuthRecoverAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/email-otp': {
      id: '/auth/email-otp'
      path: '/email-otp'
      fullPath: '/auth/email-otp'
      preLoaderRoute: typeof AuthEmailOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/accept-invitation': {
      id: '/auth/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/auth/accept-invitation'
      preLoaderRoute: typeof AuthAcceptInvitationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_route': {
      id: '/auth/_route'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/status-pages/': {
      id: '/_dashboardLayout/status-pages/'
      path: '/status-pages'
      fullPath: '/status-pages'
      preLoaderRoute: typeof DashboardLayoutStatusPagesIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/monitors/': {
      id: '/_dashboardLayout/monitors/'
      path: '/monitors'
      fullPath: '/monitors'
      preLoaderRoute: typeof DashboardLayoutMonitorsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/integrations/': {
      id: '/_dashboardLayout/integrations/'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashboardLayoutIntegrationsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/status-pages/create': {
      id: '/_dashboardLayout/status-pages/create'
      path: '/status-pages/create'
      fullPath: '/status-pages/create'
      preLoaderRoute: typeof DashboardLayoutStatusPagesCreateRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/status-pages/$statusPageId': {
      id: '/_dashboardLayout/status-pages/$statusPageId'
      path: '/status-pages/$statusPageId'
      fullPath: '/status-pages/$statusPageId'
      preLoaderRoute: typeof DashboardLayoutStatusPagesStatusPageIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/monitors/add': {
      id: '/_dashboardLayout/monitors/add'
      path: '/monitors/add'
      fullPath: '/monitors/add'
      preLoaderRoute: typeof DashboardLayoutMonitorsAddRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/monitors/$monitorId': {
      id: '/_dashboardLayout/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof DashboardLayoutMonitorsMonitorIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
  }
}

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutMonitorsMonitorIdRoute: typeof DashboardLayoutMonitorsMonitorIdRoute
  DashboardLayoutMonitorsAddRoute: typeof DashboardLayoutMonitorsAddRoute
  DashboardLayoutStatusPagesStatusPageIdRoute: typeof DashboardLayoutStatusPagesStatusPageIdRoute
  DashboardLayoutStatusPagesCreateRoute: typeof DashboardLayoutStatusPagesCreateRoute
  DashboardLayoutIntegrationsIndexRoute: typeof DashboardLayoutIntegrationsIndexRoute
  DashboardLayoutMonitorsIndexRoute: typeof DashboardLayoutMonitorsIndexRoute
  DashboardLayoutStatusPagesIndexRoute: typeof DashboardLayoutStatusPagesIndexRoute
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutMonitorsMonitorIdRoute: DashboardLayoutMonitorsMonitorIdRoute,
  DashboardLayoutMonitorsAddRoute: DashboardLayoutMonitorsAddRoute,
  DashboardLayoutStatusPagesStatusPageIdRoute:
    DashboardLayoutStatusPagesStatusPageIdRoute,
  DashboardLayoutStatusPagesCreateRoute: DashboardLayoutStatusPagesCreateRoute,
  DashboardLayoutIntegrationsIndexRoute: DashboardLayoutIntegrationsIndexRoute,
  DashboardLayoutMonitorsIndexRoute: DashboardLayoutMonitorsIndexRoute,
  DashboardLayoutStatusPagesIndexRoute: DashboardLayoutStatusPagesIndexRoute,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

interface AuthRouteChildren {
  AuthRouteRoute: typeof AuthRouteRoute
  AuthAcceptInvitationRoute: typeof AuthAcceptInvitationRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthEmailOtpRoute: typeof AuthEmailOtpRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthRecoverAccountRoute: typeof AuthRecoverAccountRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRouteRoute: AuthRouteRoute,
  AuthAcceptInvitationRoute: AuthAcceptInvitationRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthEmailOtpRoute: AuthEmailOtpRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthRecoverAccountRoute: AuthRecoverAccountRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
  AccountAccountViewRoute: AccountAccountViewRoute,
  AuthRoute: AuthRouteWithChildren,
  OrganizationOrganizationViewRoute: OrganizationOrganizationViewRoute,
  StatusSlugRoute: StatusSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
