/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteRouteImport } from './routes/_dashboardLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusSlugRouteImport } from './routes/status/$slug'
import { Route as OrganizationOrganizationViewRouteImport } from './routes/organization/$organizationView'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AccountAccountViewRouteImport } from './routes/account/$accountView'
import { Route as DashboardLayoutStatusPagesIndexRouteImport } from './routes/_dashboardLayout/status-pages/index'
import { Route as DashboardLayoutMonitorsIndexRouteImport } from './routes/_dashboardLayout/monitors/index'
import { Route as DashboardLayoutIntegrationsIndexRouteImport } from './routes/_dashboardLayout/integrations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardLayoutStatusPagesCreateRouteImport } from './routes/_dashboardLayout/status-pages/create'
import { Route as DashboardLayoutStatusPagesStatusPageIdRouteImport } from './routes/_dashboardLayout/status-pages/$statusPageId'
import { Route as DashboardLayoutMonitorsAddRouteImport } from './routes/_dashboardLayout/monitors/add'
import { Route as DashboardLayoutMonitorsMonitorIdRouteImport } from './routes/_dashboardLayout/monitors/$monitorId'

const DashboardLayoutRouteRoute = DashboardLayoutRouteRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrganizationViewRoute =
  OrganizationOrganizationViewRouteImport.update({
    id: '/organization/$organizationView',
    path: '/organization/$organizationView',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutStatusPagesIndexRoute =
  DashboardLayoutStatusPagesIndexRouteImport.update({
    id: '/status-pages/',
    path: '/status-pages/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMonitorsIndexRoute =
  DashboardLayoutMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutIntegrationsIndexRoute =
  DashboardLayoutIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutStatusPagesCreateRoute =
  DashboardLayoutStatusPagesCreateRouteImport.update({
    id: '/status-pages/create',
    path: '/status-pages/create',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutStatusPagesStatusPageIdRoute =
  DashboardLayoutStatusPagesStatusPageIdRouteImport.update({
    id: '/status-pages/$statusPageId',
    path: '/status-pages/$statusPageId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMonitorsAddRoute =
  DashboardLayoutMonitorsAddRouteImport.update({
    id: '/monitors/add',
    path: '/monitors/add',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMonitorsMonitorIdRoute =
  DashboardLayoutMonitorsMonitorIdRouteImport.update({
    id: '/monitors/$monitorId',
    path: '/monitors/$monitorId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/status/$slug': typeof StatusSlugRoute
  '/monitors/$monitorId': typeof DashboardLayoutMonitorsMonitorIdRoute
  '/monitors/add': typeof DashboardLayoutMonitorsAddRoute
  '/status-pages/$statusPageId': typeof DashboardLayoutStatusPagesStatusPageIdRoute
  '/status-pages/create': typeof DashboardLayoutStatusPagesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations': typeof DashboardLayoutIntegrationsIndexRoute
  '/monitors': typeof DashboardLayoutMonitorsIndexRoute
  '/status-pages': typeof DashboardLayoutStatusPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/status/$slug': typeof StatusSlugRoute
  '/monitors/$monitorId': typeof DashboardLayoutMonitorsMonitorIdRoute
  '/monitors/add': typeof DashboardLayoutMonitorsAddRoute
  '/status-pages/$statusPageId': typeof DashboardLayoutStatusPagesStatusPageIdRoute
  '/status-pages/create': typeof DashboardLayoutStatusPagesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations': typeof DashboardLayoutIntegrationsIndexRoute
  '/monitors': typeof DashboardLayoutMonitorsIndexRoute
  '/status-pages': typeof DashboardLayoutStatusPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteRouteWithChildren
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/status/$slug': typeof StatusSlugRoute
  '/_dashboardLayout/monitors/$monitorId': typeof DashboardLayoutMonitorsMonitorIdRoute
  '/_dashboardLayout/monitors/add': typeof DashboardLayoutMonitorsAddRoute
  '/_dashboardLayout/status-pages/$statusPageId': typeof DashboardLayoutStatusPagesStatusPageIdRoute
  '/_dashboardLayout/status-pages/create': typeof DashboardLayoutStatusPagesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboardLayout/integrations/': typeof DashboardLayoutIntegrationsIndexRoute
  '/_dashboardLayout/monitors/': typeof DashboardLayoutMonitorsIndexRoute
  '/_dashboardLayout/status-pages/': typeof DashboardLayoutStatusPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/organization/$organizationView'
    | '/status/$slug'
    | '/monitors/$monitorId'
    | '/monitors/add'
    | '/status-pages/$statusPageId'
    | '/status-pages/create'
    | '/api/auth/$'
    | '/integrations'
    | '/monitors'
    | '/status-pages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/organization/$organizationView'
    | '/status/$slug'
    | '/monitors/$monitorId'
    | '/monitors/add'
    | '/status-pages/$statusPageId'
    | '/status-pages/create'
    | '/api/auth/$'
    | '/integrations'
    | '/monitors'
    | '/status-pages'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/organization/$organizationView'
    | '/status/$slug'
    | '/_dashboardLayout/monitors/$monitorId'
    | '/_dashboardLayout/monitors/add'
    | '/_dashboardLayout/status-pages/$statusPageId'
    | '/_dashboardLayout/status-pages/create'
    | '/api/auth/$'
    | '/_dashboardLayout/integrations/'
    | '/_dashboardLayout/monitors/'
    | '/_dashboardLayout/status-pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
  AccountAccountViewRoute: typeof AccountAccountViewRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  OrganizationOrganizationViewRoute: typeof OrganizationOrganizationViewRoute
  StatusSlugRoute: typeof StatusSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$organizationView': {
      id: '/organization/$organizationView'
      path: '/organization/$organizationView'
      fullPath: '/organization/$organizationView'
      preLoaderRoute: typeof OrganizationOrganizationViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/status-pages/': {
      id: '/_dashboardLayout/status-pages/'
      path: '/status-pages'
      fullPath: '/status-pages'
      preLoaderRoute: typeof DashboardLayoutStatusPagesIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/monitors/': {
      id: '/_dashboardLayout/monitors/'
      path: '/monitors'
      fullPath: '/monitors'
      preLoaderRoute: typeof DashboardLayoutMonitorsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/integrations/': {
      id: '/_dashboardLayout/integrations/'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashboardLayoutIntegrationsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/status-pages/create': {
      id: '/_dashboardLayout/status-pages/create'
      path: '/status-pages/create'
      fullPath: '/status-pages/create'
      preLoaderRoute: typeof DashboardLayoutStatusPagesCreateRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/status-pages/$statusPageId': {
      id: '/_dashboardLayout/status-pages/$statusPageId'
      path: '/status-pages/$statusPageId'
      fullPath: '/status-pages/$statusPageId'
      preLoaderRoute: typeof DashboardLayoutStatusPagesStatusPageIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/monitors/add': {
      id: '/_dashboardLayout/monitors/add'
      path: '/monitors/add'
      fullPath: '/monitors/add'
      preLoaderRoute: typeof DashboardLayoutMonitorsAddRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/monitors/$monitorId': {
      id: '/_dashboardLayout/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof DashboardLayoutMonitorsMonitorIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
  }
}

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutMonitorsMonitorIdRoute: typeof DashboardLayoutMonitorsMonitorIdRoute
  DashboardLayoutMonitorsAddRoute: typeof DashboardLayoutMonitorsAddRoute
  DashboardLayoutStatusPagesStatusPageIdRoute: typeof DashboardLayoutStatusPagesStatusPageIdRoute
  DashboardLayoutStatusPagesCreateRoute: typeof DashboardLayoutStatusPagesCreateRoute
  DashboardLayoutIntegrationsIndexRoute: typeof DashboardLayoutIntegrationsIndexRoute
  DashboardLayoutMonitorsIndexRoute: typeof DashboardLayoutMonitorsIndexRoute
  DashboardLayoutStatusPagesIndexRoute: typeof DashboardLayoutStatusPagesIndexRoute
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutMonitorsMonitorIdRoute: DashboardLayoutMonitorsMonitorIdRoute,
  DashboardLayoutMonitorsAddRoute: DashboardLayoutMonitorsAddRoute,
  DashboardLayoutStatusPagesStatusPageIdRoute:
    DashboardLayoutStatusPagesStatusPageIdRoute,
  DashboardLayoutStatusPagesCreateRoute: DashboardLayoutStatusPagesCreateRoute,
  DashboardLayoutIntegrationsIndexRoute: DashboardLayoutIntegrationsIndexRoute,
  DashboardLayoutMonitorsIndexRoute: DashboardLayoutMonitorsIndexRoute,
  DashboardLayoutStatusPagesIndexRoute: DashboardLayoutStatusPagesIndexRoute,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
  AccountAccountViewRoute: AccountAccountViewRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  OrganizationOrganizationViewRoute: OrganizationOrganizationViewRoute,
  StatusSlugRoute: StatusSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
