/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DashboardLayoutRouteRouteImport } from './routes/_dashboardLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRecoverAccountRouteImport } from './routes/auth/recover-account'
import { Route as AuthMagicLinkRouteImport } from './routes/auth/magic-link'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailOtpRouteImport } from './routes/auth/email-otp'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAcceptInvitationRouteImport } from './routes/auth/accept-invitation'
import { Route as DashboardLayoutMonitorsIndexRouteImport } from './routes/_dashboardLayout/monitors/index'
import { Route as DashboardLayoutIntegrationsIndexRouteImport } from './routes/_dashboardLayout/integrations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardLayoutOrganizationOrganizationViewRouteImport } from './routes/_dashboardLayout/organization/$organizationView'
import { Route as DashboardLayoutMonitorsAddRouteImport } from './routes/_dashboardLayout/monitors/add'
import { Route as DashboardLayoutMonitorsMonitorIdRouteImport } from './routes/_dashboardLayout/monitors/$monitorId'
import { Route as DashboardLayoutAccountAccountViewRouteImport } from './routes/_dashboardLayout/account/$accountView'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRouteRoute = DashboardLayoutRouteRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRecoverAccountRoute = AuthRecoverAccountRouteImport.update({
  id: '/recover-account',
  path: '/recover-account',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEmailOtpRoute = AuthEmailOtpRouteImport.update({
  id: '/email-otp',
  path: '/email-otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAcceptInvitationRoute = AuthAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardLayoutMonitorsIndexRoute =
  DashboardLayoutMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutIntegrationsIndexRoute =
  DashboardLayoutIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutOrganizationOrganizationViewRoute =
  DashboardLayoutOrganizationOrganizationViewRouteImport.update({
    id: '/organization/$organizationView',
    path: '/organization/$organizationView',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMonitorsAddRoute =
  DashboardLayoutMonitorsAddRouteImport.update({
    id: '/monitors/add',
    path: '/monitors/add',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutMonitorsMonitorIdRoute =
  DashboardLayoutMonitorsMonitorIdRouteImport.update({
    id: '/monitors/$monitorId',
    path: '/monitors/$monitorId',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAccountAccountViewRoute =
  DashboardLayoutAccountAccountViewRouteImport.update({
    id: '/account/$accountView',
    path: '/account/$accountView',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-otp': typeof AuthEmailOtpRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/account/$accountView': typeof DashboardLayoutAccountAccountViewRoute
  '/monitors/$monitorId': typeof DashboardLayoutMonitorsMonitorIdRoute
  '/monitors/add': typeof DashboardLayoutMonitorsAddRoute
  '/organization/$organizationView': typeof DashboardLayoutOrganizationOrganizationViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations': typeof DashboardLayoutIntegrationsIndexRoute
  '/monitors': typeof DashboardLayoutMonitorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-otp': typeof AuthEmailOtpRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/account/$accountView': typeof DashboardLayoutAccountAccountViewRoute
  '/monitors/$monitorId': typeof DashboardLayoutMonitorsMonitorIdRoute
  '/monitors/add': typeof DashboardLayoutMonitorsAddRoute
  '/organization/$organizationView': typeof DashboardLayoutOrganizationOrganizationViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations': typeof DashboardLayoutIntegrationsIndexRoute
  '/monitors': typeof DashboardLayoutMonitorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-otp': typeof AuthEmailOtpRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/_dashboardLayout/account/$accountView': typeof DashboardLayoutAccountAccountViewRoute
  '/_dashboardLayout/monitors/$monitorId': typeof DashboardLayoutMonitorsMonitorIdRoute
  '/_dashboardLayout/monitors/add': typeof DashboardLayoutMonitorsAddRoute
  '/_dashboardLayout/organization/$organizationView': typeof DashboardLayoutOrganizationOrganizationViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboardLayout/integrations/': typeof DashboardLayoutIntegrationsIndexRoute
  '/_dashboardLayout/monitors/': typeof DashboardLayoutMonitorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/accept-invitation'
    | '/auth/callback'
    | '/auth/email-otp'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/account/$accountView'
    | '/monitors/$monitorId'
    | '/monitors/add'
    | '/organization/$organizationView'
    | '/api/auth/$'
    | '/integrations'
    | '/monitors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/accept-invitation'
    | '/auth/callback'
    | '/auth/email-otp'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/account/$accountView'
    | '/monitors/$monitorId'
    | '/monitors/add'
    | '/organization/$organizationView'
    | '/api/auth/$'
    | '/integrations'
    | '/monitors'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/auth'
    | '/auth/accept-invitation'
    | '/auth/callback'
    | '/auth/email-otp'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/_dashboardLayout/account/$accountView'
    | '/_dashboardLayout/monitors/$monitorId'
    | '/_dashboardLayout/monitors/add'
    | '/_dashboardLayout/organization/$organizationView'
    | '/api/auth/$'
    | '/_dashboardLayout/integrations/'
    | '/_dashboardLayout/monitors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/recover-account': {
      id: '/auth/recover-account'
      path: '/recover-account'
      fullPath: '/auth/recover-account'
      preLoaderRoute: typeof AuthRecoverAccountRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/email-otp': {
      id: '/auth/email-otp'
      path: '/email-otp'
      fullPath: '/auth/email-otp'
      preLoaderRoute: typeof AuthEmailOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/accept-invitation': {
      id: '/auth/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/auth/accept-invitation'
      preLoaderRoute: typeof AuthAcceptInvitationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboardLayout/monitors/': {
      id: '/_dashboardLayout/monitors/'
      path: '/monitors'
      fullPath: '/monitors'
      preLoaderRoute: typeof DashboardLayoutMonitorsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/integrations/': {
      id: '/_dashboardLayout/integrations/'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashboardLayoutIntegrationsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/organization/$organizationView': {
      id: '/_dashboardLayout/organization/$organizationView'
      path: '/organization/$organizationView'
      fullPath: '/organization/$organizationView'
      preLoaderRoute: typeof DashboardLayoutOrganizationOrganizationViewRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/monitors/add': {
      id: '/_dashboardLayout/monitors/add'
      path: '/monitors/add'
      fullPath: '/monitors/add'
      preLoaderRoute: typeof DashboardLayoutMonitorsAddRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/monitors/$monitorId': {
      id: '/_dashboardLayout/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof DashboardLayoutMonitorsMonitorIdRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/account/$accountView': {
      id: '/_dashboardLayout/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof DashboardLayoutAccountAccountViewRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
  }
}

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutAccountAccountViewRoute: typeof DashboardLayoutAccountAccountViewRoute
  DashboardLayoutMonitorsMonitorIdRoute: typeof DashboardLayoutMonitorsMonitorIdRoute
  DashboardLayoutMonitorsAddRoute: typeof DashboardLayoutMonitorsAddRoute
  DashboardLayoutOrganizationOrganizationViewRoute: typeof DashboardLayoutOrganizationOrganizationViewRoute
  DashboardLayoutIntegrationsIndexRoute: typeof DashboardLayoutIntegrationsIndexRoute
  DashboardLayoutMonitorsIndexRoute: typeof DashboardLayoutMonitorsIndexRoute
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutAccountAccountViewRoute:
    DashboardLayoutAccountAccountViewRoute,
  DashboardLayoutMonitorsMonitorIdRoute: DashboardLayoutMonitorsMonitorIdRoute,
  DashboardLayoutMonitorsAddRoute: DashboardLayoutMonitorsAddRoute,
  DashboardLayoutOrganizationOrganizationViewRoute:
    DashboardLayoutOrganizationOrganizationViewRoute,
  DashboardLayoutIntegrationsIndexRoute: DashboardLayoutIntegrationsIndexRoute,
  DashboardLayoutMonitorsIndexRoute: DashboardLayoutMonitorsIndexRoute,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthAcceptInvitationRoute: typeof AuthAcceptInvitationRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthEmailOtpRoute: typeof AuthEmailOtpRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthRecoverAccountRoute: typeof AuthRecoverAccountRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAcceptInvitationRoute: AuthAcceptInvitationRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthEmailOtpRoute: AuthEmailOtpRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthRecoverAccountRoute: AuthRecoverAccountRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
